<a href="https://colab.research.google.com/github/sofyadmitrieva/python-course/blob/main/2_types_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(c) В.И. Фирсанова | 2024

# Типы данных в Python

1. **Числовые типы**:
   - `int` integer, целое число `7`
   - `float` число с плавающей точкой (десятичная дробь) `7.1`

2. **Булевы перменные**:
   - `Bool` Boolean, принимает значения `True` или `False`

3. **Наборы, последовательности**:
   - `str` string, строка `"hello"`
   - `list`, список `[1, 7.1, "hello"]`, изменяемая последовательность
    - *вложенный список* состоит из множества списков `[[0, 1, 2], [3, 4]]`
   - `tuple`, кортеж `(1, 7.1, "hello), неизменяемая последовательность
    - в кортежах нельзя удалять, добавлять данные; они занимают меньше памяти
   - `dict`, dictionary, словарь `{"number": 1, "word": "hello"}`, пары ключей и значений (key-query)
    - в этом примере ключами будут `"number"` и `"word"`, а значениями - `1` и `"hello"`
  - `set`, множество, неупорядоченный набор уникальных элементов `{1, 2, 3}`
  - `frozenset`, неизменяемое множество (аналог кортежа по отношению к спискам)

4. **None**:
   - `None` можно использовать для создания пустого элемента, как плейсхолдер в функции, для проверки факта наличия объекта в переменной и т.д.

Задачи

1. Угадай число

In [2]:
import random # библиотека для генерации случайных чисел

# генерируем случайное целое число (random integer) от 0 до 10
# функция randint принимает два аргумента: диапазон генерации
magic_number = random.randint(0, 10)

# запросите у пользователя ввод числа
user_number = int(input("Введите число: "))

if user_number == magic_number: # проверка на совпадение значений
  print('Поздравляю, вы угадали!')
else:
  print('А вот и нет! Это число', magic_number)

Введите число: 3
А вот и нет! Это число 0

Обратите внимание на строку `print('А вот и нет! Это число', magic_number)`

`print` может принимать несколько аргументов через запятую и выводить на экран их все!

Используйте это в следующем задании.

2. Приветствие

In [3]:
# запросите у пользователя его имя
# вспомните, чем input(int()) отличается от input()
user_name = input("Введите ваше имя: ")

# выведите на экран любое приветствие для пользователя
print('Привет, ', user_name)

Введите ваше имя: Соня
Привет,  Соня

3. Конвертер температур

In [9]:
# запросите у пользователя температуру в градусах Цельсия:
# это должно быть дробное числом (float)
celcius_temperature = float(input('Введите температуру в градусах Цельсия: '))
# конвертируйте температуру из градусов Цельсия в градусы Фаренгейта:
# вспомните или найдите формулу и используйте арифметические операции python для расчетов
fahrenheit_temperature = 1.8 * celcius_temperature + 32

# выведите результат на экран:
# используйте любые текстовые формулировки, чтобы показать число,
# которое вы получили от пользователя, и результат расчетов
print('Температура в градусах Цельсия', celcius_temperature)
print('Температура в градусах Фаренгейта', fahrenheit_temperature)

Введите температуру в градусах Цельсия: 8
Температура в градусах Цельсия 8.0
Температура в градусах Фаренгейта 46.4

Как вывести на экран несколько строк?

- Можно вызвать `print` несколько раз

```
print('Вот первая строка')
print('А это вторая строка')
```
- Можно использовать `\n` - символ новой строки

```
print('Вот первая строка \n А это вторая строка')
```

4. Округление и вывод с помощью новой строки

In [17]:
# результат расчетов в задаче 3 сохранился в переменных
# воспользуемся этим преимуществом!

# округлите оба значения температур в градусах Цельсия и в градусах Фаргентейта
# вы можете преобразовать результат к виду целого числа с помощью int(n); n - число для преобразования
# либо воспользоваться функцией round(n, k), указав в аргументах функции количество знаков после запятой k
# попробуйте оба варианта!
celcius_int = int(celcius_temperature)
fahrenheit_int = int(fahrenheit_temperature)

# теперь выведите на экран оба числа
# сделайте это в одну строчку кода:
# используйте символ новой строки, подумайте, куда его добавить
print(f'Температура в градусах Цельсия {celcius_int}\nТемпература в градусах Фаренгейта {fahrenheit_int}')

Температура в градусах Цельсия 8
Температура в градусах Фаренгейта 46

В задании 4 нам может помочь свойство конкатенации строк.

`print('Hello' + ' ' +'World')`

Но сложение строки с числом невозможно в питоне. Что делать?

5. Конвертирование типов данных

In [18]:
# преобразуйте округленные значения температур к виду строк, применив str(n),
# где n - то, что вы хотите преобразовать к виду строки
celcius_str = str(celcius_int)
farenheit_str = str(fahrenheit_int)

# выведите на экран результат:
# используйте конкатенацию строк вместо запятой в функции print
print('Температура в градусах Цельсия '+ celcius_str + '\nТемпература в градусах Фаренгейта ' + farenheit_str)

Температура в градусах Цельсия 8
Температура в градусах Фаренгейта 46

Чтобы преобразовать один тип данных в другой, мы вызываем функцию, обозначающую этот тип.

Закрепим новый материал.

6. Калькулятор

In [24]:
# запросите у пользователя 2 целых числа
# выполните операции сложения, вычитания, умножения и возведения каждого из чисел во вторую степень
# выведите результат на экран

num1,num2 = int(input("Введите первое число ")), int(input("Введите второе число "))
num3 = num1 + num2
num4 = num1 - num2
num5 = num1 * num2
num6 = num1**2
num7 = num2**2

print(f'Результат сложения {num3} \nРезультат вычитания {num4} \nРезультат умножения {num5} \nРезультат возведения во вторую степень первого числа {num6} \nРезультат возведения во вторую степень второго числа {num7}')

Введите первое число 6
Введите второе число 3
Результат сложения 9
Результат вычитания 3
Результат умножения 18
Результат возведения во вторую степень первого числа 36
Результат возведения во вторую степень второго числа 9

7. Анкета

In [25]:
# вспомним множественное присваивание в python
# a, b, c = 0, 1, 2
# используйте множественное присваивание,
# чтобы одной строчкой кода запросить у пользователя имя, возраст и профессию
# выведите на экран полученную информацию

### ваш код здесь ###
name, age, occupation = input('Ваше имя '), input('Ваш возраст '), input('Ваша профессия ')
print(f'Имя: {name} \nВозраст: {age} \nПрофессия: {occupation}')

Ваше имя Соня
Ваш возраст 24
Ваша профессия переводчик
Имя: Соня
Возраст: 24
Профессия: переводчик

8. Поменять местами переменные

In [26]:
# множественное присваивание иногда очень полезно
# запросите у пользователя две любые переменные
# это может быть строка или число, на ваш выбор

# поменяйте их местами одной строчкой кода:
# запишите в первую переменную информацию из второй,
# а во вторую переменную - информацию из первой, используя множественное присваивание

# выведите на экран промежуточные и итоговые результаты

### ваш код здесь ###
variable1 = input('Введите информацию в первую переменную ')
variable2 = input('Введите информацию во вторую переменную ')
print('В первой переменной хранится ', variable1, '\nВо второй переменной хранится ', variable2)
print('Меняем местами...')
variable1, variable2 = variable2, variable1
print('В первой переменной хранится ', variable1, '\nВо второй переменной хранится ', variable2)

Введите информацию в первую переменную 1
Введите информацию во вторую переменную 2
В первой переменной хранится  1
Во второй переменной хранится  2
Меняем местами...
В первой переменной хранится  2
Во второй переменной хранится  1

9. Дописать функцию

In [28]:
# чаще мы используем множественное присваивание в фунциональном программировании
# например, эта функция считает сумму и произведение двух чисел
# функция принимает на вход (почти как input!) 2 числа
# эти числа запишутся в переменные a и b
def sum_and_product(a, b):
    # напишите здесь код для расчета суммы чисел a и b
    total_sum = a + b
    # а сюда допишите код для подсчета их произведения
    product = a * b
    # функция возвращает результат подсчета - два новых числа
    return total_sum, product

# настало время множественного присваивания
# мы вызывает функцию sum_and_product и передаем ей в качестве аргументов два числа - 5 и 3
# мы помним, что функция возвращает 2 новых числа,
# поэтому результат работы одной функции мы записываем в две переменные: result_sum и result_product
result_sum, result_product = sum_and_product(5, 3)

# выведите на экран result_sum и result_product
print('Сумма:', result_sum)
print('Произведение:', result_product)

Сумма: 8
Произведение: 15

10. Строка и число

In [30]:
# запросите у пользователя 2 числа, используйте str(input())
# сложите два числа, не меняя тип данных, и выведите на экран результат
# преобразуйте числа к виду нужного типа и снова сложите их, выведите результат

# это задание нам уже знакомо:
# попробуйте решить его питонично, используя как можно меньше строк кода
# какие операции можно объединить?
# в каких случаях нам не нужно создавать дополнительные переменные?


num1, num2 = str(input('Введите число ')), str(input('Введите еще одно число '))
print('Результат сложения ', num1 + num2, '\nРезультат сложения ', int(num1) + int(num2))

Введите число 5
Введите еще одно число 6
Результат сложения  56
Результат сложения  11